import { NextSSRPlugin } from '@uploadthing/react/next-ssr-plugin';
import { extractRouterConfig } from 'uploadthing/server';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ourFileRouter } from '@/app/api/uploadthing/core';
import { getCurrentUser } from '@/lib/user';
import { Mail } from 'lucide-react';

const inter = Inter({
  subsets: ['latin'],
  weight: ['400'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Tech Mall',
  description: 'Generated By Tech Mall',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getCurrentUser();
  return (
    <html lang="en" className="overflow-x-hidden" suppressHydrationWarning>
      <body className={`${inter.className} antialiased bg-muted pb-32`} suppressHydrationWarning>
        <div className="text-xs ">
          <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />
          {children}
          {user && (
            <div className="fixed bottom-0 cursor-pointer right-20 p-3 px-4 bg-primary rounded-t text-background text-xs flex gap-1 items-center ">
              <span>Tin nhắn đến</span>
              <Mail size={12} strokeWidth={2.5} />
              <span className="absolute w-4 h-4 rounded-full bg-background border border-dashed border-primary p-1 -right-2 -top-2 text-primary flex items-center justify-center">
                4
              </span>
            </div>
          )}
        </div>
      </body>
    </html>
  );
}
